name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_SECRET }}
          user: AbhiramTadepalli
          template: classic
          base: header, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes # Shows lines of code added/deleted
